### ISSUE TITLE
ValueError : Too many values to unpack

### ISSUE THREAD

**Issue by aulisius** [prajwalkr/SnapSudoku#18]
This code breaks when I'm running it with OpenCV 3.1.0. Works fine with 2.4.9

```
Traceback (most recent call last):
  File "sudoku.py", line 41, in <module>
    Sudoku(sys.argv[1])
  File "sudoku.py", line 14, in __init__
    cells = Extractor(image_path).cells
  File "W:\SnapSudoku\scripts\sudokuExtractor.py", line 20, in __init__
    sudoku = self.cropSudoku()
  File "W:\SnapSudoku\scripts\sudokuExtractor.py", line 43, in cropSudoku
    contour = self.helpers.largestContour(self.image.copy())
  File "W:\SnapSudoku\scripts\helpers.py", line 41, in largestContour
    image, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack
```

**Comment by prajwalkr** [comment]
Fixed issue! :smile:
