### ISSUE TITLE
Too many values to unpack?

### ISSUE THREAD

**Issue by ghost** [prajwalkr/SnapSudoku#31]
```
> sudo python2 sudoku.py /home/jokerowaty/SnapSudoku/test/test1.jpg
> Image loaded.
> Preprocessing... done.
> Cropping out Sudoku... done.
> Straightening image...
> Traceback (most recent call last):
>   File "sudoku.py", line 42, in <module>
>     snap_sudoku(image_path=sys.argv[1])
>   File "sudoku.py", line 32, in snap_sudoku
>     grid = ''.join(cell for cell in get_cells(image_path))
>   File "sudoku.py", line 32, in <genexpr>
>     grid = ''.join(cell for cell in get_cells(image_path))
>   File "sudoku.py", line 23, in get_cells
>     for row in Extractor(os.path.abspath(image_path)).cells:
>   File "/home/jokerowaty/SnapSudoku/scripts/sudokuExtractor.py", line 22, in __init__
>     sudoku = self.straighten(sudoku)
>   File "/home/jokerowaty/SnapSudoku/scripts/sudokuExtractor.py", line 50, in straighten
>     largest = self.helpers.largest4SideContour(sudoku.copy())
>   File "/home/jokerowaty/SnapSudoku/scripts/helpers.py", line 53, in largest4SideContour
>     image, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
> ValueError: too many values to unpack
```

Any ideas? opencv2 installed, numpy installed. Python2.7.14+

**Comment by BSatyaKishore** [comment]
You're using openCV v3, please update the 49th line in scripts/helpers.py to 
_, contours, h = cv2.findContours(

And it will work.
